openapi: "3.0.0"
info:
  title: Learn express and swagger
  description: A course segment about learning docs
  vesrion: 1.1.0
  contact:
    email: yukti@gmail.com
    url: "www.google.com"

# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: for local host- secure
#   - url: "http://localhost:4000/api/v1"
#     description: for local host - regular


servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host- secure
    variables: 
      version:
        enum:
          - v1
          - v2
      protocol:
        enum:
          - http
          - https

components: 
  securitySchemes: 
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer





  


